#! /usr/bin/env ruby

require 'socket'
load 'client.rb'
load 'config.rb'
load 'event.rb'
load 'handler.rb'
$handler = Handler.new
load 'events.rb'
Dir.open 'scripts' do |d|
  d.each do |f|
    load 'scripts/'+f unless ['.','..'].include? f
  end
end

config = Config.new
clients = []
config.getServers.each do |n,s|
  client = Client.new(s['host'],s['port'],s['nick'],s['altNick'],s['user'],s['host'],s['fullName'])
  clients.push client
end

while (true)
  events = select(clients,nil,nil,0.05)
  unless events.nil?
    events[0].each do |s|
      s.handle s.gets.chomp
    end
  end
end

